parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"UldJ":[function(require,module,exports) {
"use strict";function t(t,e){return t.reduce(function(t,r,n){var o=Math.floor(n/e);return t[o]||(t[o]=[]),t[o].push(r),t},[])}function e(t,e){return t=Math.ceil(t),e=Math.floor(e),Math.floor(Math.random()*(e-t))+t}function r(){return new Promise(function(t){chrome.tabs.getSelected(function(e){t(e.url)})})}Object.defineProperty(exports,"__esModule",{value:!0}),exports.getCurrentTabUrl=exports.getRandomInt=exports.chunk=void 0,exports.chunk=t,exports.getRandomInt=e,exports.getCurrentTabUrl=r;
},{}],"btj8":[function(require,module,exports) {
"use strict";function n(n,e){if(!(n instanceof e))throw new TypeError("Cannot call a class as a function")}function e(n,e){for(var t=0;t<e.length;t++){var r=e[t];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(n,r.key,r)}}function t(n,t,r){return t&&e(n.prototype,t),r&&e(n,r),n}Object.defineProperty(exports,"__esModule",{value:!0}),exports.ImageFetcherOnLgtmoon=exports.ImageFetcherOnLgtmFun=void 0;var r=require("./utils"),o=function(){function e(){n(this,e)}return t(e,[{key:"getRandom",value:function(){var n="https://lgtm.fun",e=function(e){if(e>0&&e<10)return"".concat(n,"/random").concat(e,".json");throw new Error("invalid random number must be 0 > number 10, ".concat(e))},t=("".concat(n,"/latest.json"),r.getRandomInt(1,9));return fetch(e(t)).then(function(n){return n.json()})}}]),e}();exports.ImageFetcherOnLgtmFun=o;var u=function(){function e(){n(this,e)}return t(e,[{key:"getRandom",value:function(){return fetch("https://lgtmoon.herokuapp.com/api/images/random").then(function(n){return n.json()}).then(function(n){return n.images.map(function(n){return{imageurl:n.url}})})}}]),e}();exports.ImageFetcherOnLgtmoon=u;
},{"./utils":"UldJ"}],"P5CY":[function(require,module,exports) {
"use strict";function e(e,n){if(!(e instanceof n))throw new TypeError("Cannot call a class as a function")}function n(e,n){for(var r=0;r<n.length;r++){var t=n[r];t.enumerable=t.enumerable||!1,t.configurable=!0,"value"in t&&(t.writable=!0),Object.defineProperty(e,t.key,t)}}function r(e,r,t){return r&&n(e.prototype,r),t&&n(e,t),e}Object.defineProperty(exports,"__esModule",{value:!0}),exports.ImageRendererOnDom=void 0;var t=require("./utils"),o=function(){function n(){e(this,n),this.rootElement=document.querySelector("#content")}return r(n,[{key:"render",value:function(e){function n(e){return'<li class="image-li">\n            <img class="lgtm-img" src="'.concat(e.imageurl,'" />\n            </li>')}var r=t.chunk(e,5).map(function(e){return'\n        <ul class="images-ul">\n            '.concat(e.map(n).reduce(function(e,n){return e+n},""),"\n        </ul>\n        ")}).map(function(e){return'<div class="images-ul-wrapper">'.concat(e,"</div>")}).reduce(function(e,n){return e+n},"");this.rootElement.innerHTML=r}}]),n}();exports.ImageRendererOnDom=o;
},{"./utils":"UldJ"}],"YSF2":[function(require,module,exports) {
"use strict";function e(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}function t(e,t){for(var n=0;n<t.length;n++){var r=t[n];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(e,r.key,r)}}function n(e,n,r){return n&&t(e.prototype,n),r&&t(e,r),e}Object.defineProperty(exports,"__esModule",{value:!0}),exports.start=void 0;var r=require("./utils"),o=require("./fetcher"),i=require("./renderer");function a(e){r.getCurrentTabUrl().then(function(t){return t.includes("https://github.com")?function(e){return"![img](".concat(e,' "img")')}(e):e}).then(function(e){return navigator.clipboard.writeText(e)}).then(function(){console.log("copied to clipboard")},function(e){console.log("failed to copy",e)})}var c=function(){function t(n,r){e(this,t),this.imageFetcher=n,this.imageRenderer=r}return n(t,[{key:"loadAndShowImages",value:function(){var e=this;this.imageFetcher.getRandom().then(function(t){e.imageRenderer.render(t)})}}]),t}();function u(){var e,t=new c(new o.ImageFetcherOnLgtmoon,new i.ImageRendererOnDom);null===(e=document.querySelector(".more-load-button"))||void 0===e||e.addEventListener("click",function(){return t.loadAndShowImages()}),document.addEventListener("click",function(e){if((null==e?void 0:e.target)instanceof Element&&"lgtm-img"===(null==e?void 0:e.target.getAttribute("class"))){var t=e.target.getAttribute("src");t&&a(t)}}),t.loadAndShowImages()}exports.start=u;
},{"./utils":"UldJ","./fetcher":"btj8","./renderer":"P5CY"}],"MEcY":[function(require,module,exports) {
"use strict";var r=require("./src/app");(0,r.start)();
},{"./src/app":"YSF2"}]},{},["MEcY"], null)
//# sourceMappingURL=/popup.js.map